"""create procurement requests

Revision ID: 80a9866ef0aa
Revises:
Create Date: 2026-09-08 23:42:26.342564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80a9866ef0aa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "procurement_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "estimated_budget", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("delivery_timeline", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("procurement_requests")
    # ### end Alembic commands ###
